-- BORRAR BASE DE DATOS SI EXISTE
DROP DATABASE IF EXISTS COMPRASWEB;
CREATE DATABASE COMPRASWEB;
USE COMPRASWEB;

-- TABLA CLIENTE
CREATE TABLE CLIENTE (
    NIF VARCHAR(9) PRIMARY KEY,
    NOMBRE VARCHAR(40),
    APELLIDO VARCHAR(40),
    CP VARCHAR(5),
    DIRECCION VARCHAR(40),
    CIUDAD VARCHAR(40),
    CLAVE VARCHAR(255) NOT NULL
) ENGINE=InnoDB;

-- TABLA CATEGORIA
CREATE TABLE CATEGORIA (
    ID_CATEGORIA VARCHAR(5) PRIMARY KEY,
    NOMBRE VARCHAR(40)
) ENGINE=InnoDB;

-- TABLA ALMACEN
CREATE TABLE ALMACEN (
    NUM_ALMACEN INT AUTO_INCREMENT PRIMARY KEY,
    LOCALIDAD VARCHAR(40)
) ENGINE=InnoDB;

-- TABLA PRODUCTO
CREATE TABLE PRODUCTO (
    ID_PRODUCTO VARCHAR(5) PRIMARY KEY,
    NOMBRE VARCHAR(40),
    PRECIO DOUBLE,
    ID_CATEGORIA VARCHAR(5),
    CONSTRAINT FK_PROD_CAT FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA)
) ENGINE=InnoDB;

-- TABLA COMPRA
CREATE TABLE COMPRA (
    NIF VARCHAR(9),
    ID_PRODUCTO VARCHAR(5),
    FECHA_COMPRA DATE,
    UNIDADES INT,
    PRIMARY KEY (NIF, ID_PRODUCTO, FECHA_COMPRA),
    CONSTRAINT FK_COM_CLI FOREIGN KEY (NIF) REFERENCES CLIENTE(NIF),
    CONSTRAINT FK_COM_PRO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO)
) ENGINE=InnoDB;

-- TABLA ALMACENA
CREATE TABLE ALMACENA (
    NUM_ALMACEN INT,
    ID_PRODUCTO VARCHAR(5),
    CANTIDAD INT,
    PRIMARY KEY (NUM_ALMACEN, ID_PRODUCTO),
    CONSTRAINT FK_ALM_ALM FOREIGN KEY (NUM_ALMACEN) REFERENCES ALMACEN(NUM_ALMACEN),
    CONSTRAINT FK_ALM_PRO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO)
) ENGINE=InnoDB;
